### Get All Posts
GET http://localhost:5000/api/posts

###

### Add a New Post
POST http://localhost:5000/api/posts
Content-Type: application/json

{
  "message": "This is the content of the sample post.",
  "sender": "Sample Author"
}