### Get All Posts
GET http://localhost:5000/post

###

### Get Post by ID
GET http://localhost:5000/post/695425b24e93c18d9233f09a

###

### Get Posts by Sender
GET http://localhost:5000/post?sender=Sample%20Author

###

### Update a Post
PUT http://localhost:5000/post/695425b24e93c18d9233f09a
Content-Type: application/json

{
  "message": "Updated message content.",
  "sender": "Updated Sender"
}

###

### Add a New Post
POST http://localhost:5000/post
Content-Type: application/json

{
  "message": "This is the content of the sample post.",
  "sender": "Sample Author"
}

###

### Create a new comment
POST http://localhost:5000/comments
Content-Type: application/json

{
  "postId": "64f1a2b3c9e77a0012345678",
  "sender": "user_123",
  "message": "This is a comment on the post"
}

###

### Get all comments
GET http://localhost:5000/comments

###

### Get a comment by ID
GET http://localhost:5000/comments/64f1b2c3d9e77a0098765432

###

### Get all comments for a specific post
GET http://localhost:5000/comments?postId=64f1a2b3c9e77a0012345678

###

### Update a comment (full replacement)
PUT http://localhost:5000/comments/64f1b2c3d9e77a0098765432
Content-Type: application/json

{
  "postId": "64f1a2b3c9e77a0012345678",
  "sender": "user_123",
  "message": "Updated comment content"
}

###

### Delete a comment
DELETE http://localhost:5000/comments/64f1b2c3d9e77a0098765432